FROM debian:latest
RUN apt-get update && apt-get install -y snort python3 python3-pip
COPY configs/snort.conf /etc/snort/snort.conf
CMD ["snort", "-c", "/etc/snort/snort.conf", "-i", "eth0", "-A", "fast"]
